### ISSUE TITLE
Add Swift Package Manager support

### ISSUE THREAD

**Issue by ceeK** [ceeK/Solar#11]

**Comment by armintelker** [comment]
Hey since the SPM community is growing we should think about to implement this here.

**Comment by amerikan** [comment]
Yes, please!

I thought maybe it was already enabled.

![Screen Shot 2020-05-24 at 1 26 35 PM](https://user-images.githubusercontent.com/179356/82764241-35336b80-9dc2-11ea-97c6-a46e3806aab9.png)

I'm relatively new to the iOS ecosystem. But based on the message, it might just needs a Package.swift manifest? Here is an example project with manifest: https://github.com/apple/example-package-dealer

**Comment by amerikan** [comment]
I played with it and got it working: https://github.com/ceeK/Solar/pull/46

**Comment by 1ec5** [comment]
SPM support is now implemented in #46, #47, and #49. @ceeK, do you have a preference between these implementations?
