### ISSUE TITLE
Xcode 10 build error

### ISSUE THREAD

**Issue by euroboy** [ceeK/Solar#34]
After updating Xcode to version 10, it shows me the following error on `import Solar`:
**Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler.**
Any ideas how to fix this?

**Comment by raysarebest** [comment]
You've compiled Solar using Swift 4.1.2, but your app is in Swift 4.2. You need to recompile Solar using Swift 4.2

**Comment by euroboy** [comment]
@raysarebest Thank you for help, it worked.
