### ISSUE TITLE
Add sun position

### ISSUE THREAD

**Issue by jhurliman** [ceeK/Solar#4]
Would you consider adding sun position information to this library, i.e. altitude and azimuth? See the docs at https://github.com/mourner/suncalc for an example. Feel free to close this issue if it's out of scope.

**Comment by ceeK** [comment]
Hi John,

I had this in the back of my mind and it's something I'd like to do. I've just glanced over the sunCalc source code and it doesn't seem like it'd be that time consuming. I'll keep this issue open as an enhancement and try set aside some time to it, as it seems like it would be fairly useful to people.

**Comment by ceeK** [comment]
Closing this for the time being as I don't imagine this will be in scope for awhile.
