### ISSUE TITLE
Xcode 12.5 Build Warning

### ISSUE THREAD

**Issue by sepw** [ceeK/Solar#54]
I get the following build warning when building with Xcode 12.5:

```
/Users/me/Library/Developer/Xcode/DerivedData/Project/SourcePackages/checkouts/Solar/Package.swift The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99.
```

This appears to have been fixed for `Solar.podspec` by `07e6310`. Solar's `Package.swift` was likely overlooked. Please update the `Package.swift` deployment target to be consistent with the `Solar.podspec`.

**Comment by 1ec5** [comment]
Yes, it looks like #53 only touched the CocoaPods podspec and Xcode project (for Carthage-based builds).

/cc @MaximAlien

**Comment by MaximAlien** [comment]
Sorry, looks like I've missed that. Created PR which fixes this in https://github.com/ceeK/Solar/pull/55.

**Comment by sepw** [comment]
That's great! Thank you for fixing this issue so quickly.
