### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by ceeK** [ceeK/Solar#9]
This will need fleshing out, but a good test suite would add confidence in using the library. Quick + Nimble preferred.

**Comment by grumBit** [comment]
Hi Chris,

I had a quick skim of Quick + Nimble.  They look the business.  If you're happy, I'll have a crack at using them for the following testing suggestions;
-     accurate to within +/-configurable mins of timeanddate.com
-     sunset / sunrise for all zeniths (on a day in London)
-     same output date as forDate (all tests)
-     forDate at start / end day (on a day in London)
-     forDate at start / end year (on a day in London)
-     forDate once a month for a year across a number of locations; e.g. London, Melbourne, Boston, Beijing
-     forDate at start / end of location with continuous day / night (e.g. Murmansk) for all zeniths
-     start/end daylight savings - Melbourne
-     Non-standard timezone - e.g. South Australia (ACST) is GMT +9:30

If you've any thought on these or other test, let me know.  I may not get a chance to look at it till mid next week.

Cheers, Graham.

**Comment by ceeK** [comment]
Implemented in 2.0.0.
